### ISSUE TITLE
"No indicators" on Manjaro/Arch

### ISSUE THREAD

**Issue by FreaxMATE** [AyatanaIndicators/ayatana-indicator-session#56]
I compiled ayatana-ido libayatana-indicator libayatana-common ayatana-indicator-session from source on an up-to-date Manjaro MATE. However when adding the mate-indicators-applet to the panel there only appears a label with "No Indicators". When looking into the installed files of ayatana-indicator-session I see the

```bash
freaxmate@manjaro ~> ls /etc/xdg/autostart/
at-spi-dbus-bus.desktop            mate-maximus-autostart.desktop  org.gnome.Evolution-alarm-notify.desktop            user-dirs-update-gtk.desktop
ayatana-indicator-session.desktop  mate-power-manager.desktop      org.gnome.SettingsDaemon.DiskUtilityNotify.desktop  vboxclient.desktop
blueman.desktop                    mate-screensaver.desktop        pamac-tray-budgie.desktop                           vmware-user.desktop
gnome-keyring-pkcs11.desktop       mate-settings-daemon.desktop    pamac-tray.desktop
gnome-keyring-secrets.desktop      msm_notifier.desktop            polkit-mate-authentication-agent-1.desktop
gnome-keyring-ssh.desktop          nm-applet.desktop               spice-vdagent.desktop
freaxmate@manjaro ~> cat /etc/xdg/autostart/ayatana-indicator-session.desktop
[Desktop Entry]
Type=Application
Name=Ayatana Indicator Session
Exec=/usr/libexec/ayatana-indicator-session/ayatana-indicator-session-service
OnlyShowIn=Unity;MATE;XFCE;Budgie:GNOME;
NoDisplay=true
StartupNotify=false
Terminal=false
```
so whent trying to run the executable from terminal I get this error:
```bash
freaxmate@manjaro ~> /usr/libexec/ayatana-indicator-session/ayatana-indicator-session-service

** (process:1284): WARNING **: 23:20:44.008: exiting: service couldn't acquire, or lost ownership of, busname
```
How can this be fixed?

**Comment by tari01** [comment]
@FreaxMATE 

You need **mate-indicator-applet** from the AUR. Info here:
https://tari.in/www/articles/ayatana/

**Comment by tari01** [comment]
I am closing this as it should be resolved. If you have any more questions/problems please feel free to open an issue any time.

**Comment by FreaxMATE** [comment]
And you're right (https://aur.archlinux.org/packages/ayatana-indicator-sound/#comment-831816) after downgrading vala to an earlier version it works. However one thing is still not working after setting everything up according to your website: Some menu items only show "Failed to create IDO object" although ayatana-ido installs without issues.
![Peek 2021-10-20 10-10](https://user-images.githubusercontent.com/49864414/138054088-e06d7db6-78cf-4ab1-8cf2-3d4ffb2a800c.gif)
Does this happen also to you?

**Comment by tari01** [comment]
> And you're right (https://aur.archlinux.org/packages/ayatana-indicator-sound/#comment-831816) after downgrading vala to an earlier version it works.

The fix is on the way: https://github.com/AyatanaIndicators/ayatana-indicator-sound/pull/37

> However one thing is still not working after setting everything up according to your website: Some menu items only show "Failed to create IDO object" although ayatana-ido installs without issues.

We have recently changed some IDO names all across Ayatana. If you have a mix of components installed from source and the AUR, you might have this problem. You can fix this by installing everything you need from source in the same order as on the website.
